### ISSUE TITLE
Winding design

### ISSUE THREAD

**Issue by crobarcro** [WISDEM/GeneratorSE#2]
Hi, could you explain the winding design assumed in GeneratorSE please? i.e. how many coil sides to a slot? I'm confused by the picture in the manual and the numbers. 

Is there 3 slots per pole (or 6 slots per pole-pair) with each coil having a slot pitch of 1? I.e. is each coil wound around a single tooth, and each slot have two coil sides in it?

**Comment by ptrbortolotti** [comment]
We apologize, we've never got to address this issue. Three years ago we merged the old GeneratorSE into WISDEM. Now we're revamping this repo for some newer codes. Please reopen any new issue if still relevant. Thank you, WISDEM team
